{
 "title": "CryptingUp",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "customer",
    "query": "import \"influxdata/influxdb/v1\"\r\n\r\nv1.tagValues(\r\n  bucket: \"grafana\",\r\n  tag: \"customer_id\",\r\n  predicate: (r) => true,\r\n  start: -1d\r\n)"
   },
   {
    "name": "most_revaluated_exchange_id",
    "query": "from(bucket: \"grafana\")\r\n  |> range(start: -2m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"portfolio\")\r\n  |> filter(fn: (r) => r.customer_id == \"${customer}\" and r.most_revaluated== \"true\")\r\n  |> keep(columns: [\"_time\",\"exchange_id\", \"asset_id\"])\r\n  |> group()\r\n  |> distinct(column: \"exchange_id\")"
   },
   {
    "name": "most_revaluated_asset_id",
    "query": "from(bucket: \"grafana\")\r\n  |> range(start: -2m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"portfolio\")\r\n  |> filter(fn: (r) => r.customer_id == \"${customer}\" and r.most_revaluated== \"true\")\r\n  |> keep(columns: [\"_time\",\"exchange_id\", \"asset_id\"])\r\n  |> group()\r\n  |> distinct(column: \"asset_id\")"
   },
   {
    "name": "most_devaluated_exchange_id",
    "query": "from(bucket: \"grafana\")\r\n  |> range(start: -2m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"portfolio\")\r\n  |> filter(fn: (r) => r.customer_id == \"${customer}\" and r.most_devaluated== \"true\")\r\n  |> keep(columns: [\"_time\",\"exchange_id\", \"asset_id\"])\r\n  |> group()\r\n  |> distinct(column: \"exchange_id\")"
   },
   {
    "name": "most_devaluated_asset_id",
    "query": "from(bucket: \"grafana\")\r\n  |> range(start: -2m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"portfolio\")\r\n  |> filter(fn: (r) => r.customer_id == \"${customer}\" and r.most_devaluated== \"true\")\r\n  |> keep(columns: [\"_time\",\"exchange_id\", \"asset_id\"])\r\n  |> group()\r\n  |> distinct(column: \"asset_id\")"
   }
  ]
 },
 "panels": [
  { "title": "Reporting Panel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Portfolio",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"grafana\")\r\n  |> range(start: -2m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"portfolio\")\r\n  |> filter(fn: (r) => r[\"customer_id\"] == \"${customer}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> drop(columns:[\"most_revaluated\",\"most_devaluated\", \"customer_id\"])\r\n  |> group(columns:[\"asset_id\", \"exchange_id\"])\r\n  |> rename(columns: {_value: \"\"})"
    }
   ]
  },
  {
   "title": "Portfolio (Cumulative)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"grafana\")\r\n  |> range(start: -1h, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"portfolio\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\" and r.customer_id == \"${customer}\")\r\n  |> group(columns: [\"customer_id\"])\r\n  |> aggregateWindow(every: 2m, fn: sum, createEmpty: true)\r\n  |> drop(columns:[\"customer_id\"])\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Top Performant Asset in Portfolio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"grafana\")\r\n  |> range(start: -1h, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"market\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"price\" and r.base_asset == \"${most_revaluated_asset_id}\" and r.exchange_id == \"${most_revaluated_exchange_id}\")"
    }
   ]
  },
  {
   "title": "Worst Performant Asset in Portfolio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"grafana\")\r\n  |> range(start: -1h, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"market\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"price\" and r.base_asset == \"${most_devaluated_asset_id}\" and r.exchange_id == \"${most_devaluated_exchange_id}\")"
    }
   ]
  },
  { "title": "Alerts Panel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Target Price Exceeded Alert",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"grafana\")\r\n  |> range(start: -2m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"targetpriceexceededalert\" and r.customer_id == \"${customer}\" \r\n  and (r._field == \"target_price\" or r._field == \"current_price\"))\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"asset_id\"])\r\n  |> drop(columns: [\"_field\", \"_measurement\", \"customer_id\", \"_start\", \"_stop\"])\r\n  "
    }
   ]
  },
  {
   "title": "Devaluation Alert",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"grafana\")\r\n  |> range(start: -2m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"devaluationalert\" and r.customer_id == \"${customer}\" and r._field == \"event_ts\")\r\n  |> group(columns: [\"asset_id\"])\r\n  |> rename(columns: {_value: \"event_ts\"})\r\n  |> drop(columns: [\"_field\", \"_measurement\", \"customer_id\", \"_start\", \"_stop\"])"
    }
   ]
  },
  {
   "title": "Rate of Change of Assets on Loss Event Time",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"grafana\")\r\n  |> range(start: -2m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rateofchangealert\" and r.customer_id == \"${customer}\" \r\n  and (r._field == \"rate_of_change\" or r._field == \"event_time\"))\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"asset_id\"])\r\n  |> drop(columns: [\"_field\", \"_measurement\", \"customer_id\", \"_start\", \"_stop\"])\r\n  "
    }
   ]
  },
  {
   "title": "Fluctuation Alert",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"grafana\")\r\n  |> range(start: -2m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fluctuationalert\" and r.customer_id == \"${customer}\" and r._field == \"event_ts\")\r\n  |> group(columns: [\"asset_id\"])\r\n  |> rename(columns: {_value: \"event_ts\"})\r\n  |> drop(columns: [\"_field\", \"_measurement\", \"customer_id\", \"_start\", \"_stop\"])"
    }
   ]
  },
  {
   "title": "Ten Percent Loss Alert",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"grafana\")\r\n  |> range(start: -2m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tenpercentlossalert\" and r.customer_id == \"${customer}\" and r._field == \"since\")\r\n  |> group(columns: [\"asset_id\"])\r\n  |> rename(columns: {_value: \"since\"})\r\n  |> drop(columns: [\"_field\", \"_measurement\", \"customer_id\", \"_start\", \"_stop\"])"
    }
   ]
  }
 ]
}